### PR TITLE
Add server-render package compatibility

### PR DESCRIPTION
**Pull request by abecks**
This PR adds compatibility with Meteor's `server-render` package for HTML included via `HtmlWebpackPlugin`. An important note is that `server-render` must be listed below `ardatan:webpack-dev-server` in `.meteor/packages` for the correct boilerplate callback order to be registered.

Previously, this repo did not work with `server-render` because the dev server boilerplate callback executes after `server-render`'s.

### CODE REVIEW

**Comment by abecks** [comment]
On another note, I was wondering why the dev server uses `dynamicHead` and `dynamicBody`. Was there any reason it was chosen over `head` and `body`? Since `HtmlWebpackPlugin` is the replacement for Meteor's HTML bundler, I would expect it to mimic it's behavior and use the same variables? This would make switching to webpack easier if anyone is using boilerplate callbacks to access/modify `head` and `body`.

**Comment by ardatan** [comment]
Thank you @abecks!

**Comment by abecks** [comment]
Done! Thanks @ardatan

**Comment by ardatan** [comment]
Could you resolve this again :)

**Comment by abecks** [comment]
Thanks for the great package. I'm able to use this in production now!

**Comment by ardatan** [comment]
Published `0.0.8`

**Pull request merged**
